### PR TITLE
Request: Add support for CURLOPT_PROGRESSFUNCTION

### PR DESCRIPTION
**Pull request by Billiam**
Adding support for the progress callback would be useful for large downloads, displaying progress to a user.

### CODE REVIEW

**Comment by LPGhatguy** [comment]
I think I will provide support for `CURLOPT_XFERINFOFUNCTION` instead, since it's reported as being newer.

I'll see if I can get around to this tomorrow night.

**Comment by LPGhatguy** [comment]
Well, I'm swamped for the time being, but I see that you forked the repo; if you can get that working feel free to send a pull request.

**Comment by Billiam** [comment]
Added, thanks! FFI is new territory for me, but that works the way I was hoping for/expecting.

**Comment by LPGhatguy** [comment]
Looks good to me! I'll test it when I get home and merge it in.

**Comment by LPGhatguy** [comment]
This is merged and has been pushed into release 2.2.0. Thanks!

**Pull request merged**
